<?php
/**
 * FormatTestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swagger Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FormatTestTest Class Doc Comment
 *
 * @category    Class */
// * @description FormatTest
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FormatTestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "FormatTest"
     */
    public function testFormatTest()
    {

    }

    /**
     * Test attribute "integer"
     */
    public function testPropertyInteger()
    {

    }

    /**
     * Test attribute "int32"
     */
    public function testPropertyInt32()
    {

    }

    /**
     * Test attribute "int64"
     */
    public function testPropertyInt64()
    {

    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {

    }

    /**
     * Test attribute "float"
     */
    public function testPropertyFloat()
    {

    }

    /**
     * Test attribute "double"
     */
    public function testPropertyDouble()
    {

    }

    /**
     * Test attribute "string"
     */
    public function testPropertyString()
    {

    }

    /**
     * Test attribute "byte"
     */
    public function testPropertyByte()
    {

    }

    /**
     * Test attribute "binary"
     */
    public function testPropertyBinary()
    {

    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {

    }

    /**
     * Test attribute "date_time"
     */
    public function testPropertyDateTime()
    {

    }

    /**
     * Test attribute "uuid"
     */
    public function testPropertyUuid()
    {

    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {

    }

}
